# YOUTUBE_CHANNEL_ID = 'UC1dHu9GhbHH7RcHKyJdaOvA'
# DISCORD_CHANNEL_ID = 1530184263406981180
import os

DISCORD_CHANNEL_ID = int(os.getenv("DISCORD_CHANNEL_ID"))
YOUTUBE_CHANNEL_ID = os.getenv("YOUTUBE_CHANNEL_ID")
CHECK_INTERVAL = int(os.getenv("CHECK_INTERVAL", 60))